  port: /dev/ttyACM1
  duty_cycle_min: 0.005
  duty_cycle_max: 0.950
  current_min: 0.0
  current_max: 20
  brake_min: -20000.0
  brake_max: 500.0
  speed_min: -3250
  speed_max: 3250
  position_min: 0.0
  position_max: 0.0 
  servo_min: 0.15
  servo_max: 0.85
